### ISSUE TITLE
mysqldump is not recognised by Windows

### ISSUE THREAD

**Issue by sarwatfatimam** [carlouni/python-mysql-backup#1]
Hi, 

I have used your script but I am facing this issue where my command prompt does not recognise mySQLdump. The script ends up in an SQL file which has less file size than if I do it with SQLyog. Can you please let me know how you installed mySQLdump?

**Comment by carlouni** [comment]
The script runs on Linux. And you actually need the MySQL CLI client and the tar utility. On windows, you can try setting up MySQL Workbench. It contains mysqldump.exe https://dev.mysql.com/downloads/workbench/ . You'll probably need to add the Workbench binaries to the Windows path.

http://stackoverflow.com/questions/3246482/mysql-command-line-client-for-windows
